### ISSUE TITLE
Support for references

### ISSUE THREAD

**Issue by fgimian** [keepassium/KeePassium#159] opened 2021-04-25 10:51 UTC
**Describe the feature you'd like**
KeePassXC offers the ability to configure references for username and password when you have multiple entries that use the same credentials.  I am aware that KeePassXC also offers a way to specify Additional URLs in the Browser Integration pane, but in many cases this is less ideal.

e.g. Facebook and Facebook Messenger are really two separate products that use the same credentials.  Each has its own URL and its own icon.  Similar story with StackOverflow, StackExchange etc.

In those cases I use multiple entries where the 2nd (and 3rd etc.) reference credentials in the first.  This is achieved in KeePassXC using the **Clone Entry** function and requesting that username and password are replaced with references.

e.g.

![image](https://user-images.githubusercontent.com/1811813/115990657-c250f700-a607-11eb-9c6e-8579bb823f15.png)

Currently, Keepassium does not interpret these references at all, and thus cloned entries that refer to others simply won't work as the username and password displays `{REF:...}` instead of the actual value that has been fetched from the reference.

I use references for several entries in my database and this feature will allow me to authenticate against all those respective sites successfully.

**Comment by keepassium** [comment] 2021-04-25 20:18
Good news: this is already implemented and [released](https://keepassium.com/blog/keepassium-1.20/)
Bad news: field references are a premium feature... (feel free to check them in [beta](https://keepassium.com/beta))

(Closing as duplicate of #77)

**Closed** 2021-04-25 20:18 UTC
Labels: duplicate, enhancement

**Comment by fgimian** [comment] 2021-04-25 23:13
Thanks for the reply, apologies I missed this 😄  I'm hoping to buy the paid upgrade in a few weeks anyway, but just am trying out the app to see how well it works for me first.
