### ISSUE TITLE
Saving Databases erases custom Auto-Type sequence

### ISSUE THREAD

**Issue by Silun** [keepassium/KeePassium#45] opened 2019-08-03 16:47 UTC
**Describe the bug**
Saving a database in KeePassium will remove custom Auto-Type sequences.

**To Reproduce**
1. Take database from the desktop KeePass client that is filled with entries that have custom Auto-Type sequences, eg to include {totp} codes.
2. Have said database on a cloud, in my case OwnCloud
3. Open database in KeePassium from the file provider.
4. Change something - in my case I only changed the name of one key by a couple letters.
5. Wait till the sync does it's thing, then open database in Desktop again.

**Expected behavior**
Only the name of the changed entry should change, everything else should stay the same.

**Actual behavior**
All custom Auto-Type sequences in my database have been set to standard, in the process removing the custom patterns I put in there. For anybody else who stumbles across this issue, I was able to get my sequences back by syncing with a backup.

**User Information (please complete the following information):**
KeePassium iPhone SE@iOS 12.3.1, KeePass on Windows 10, OwnCloud

**Comment by keepassium** [comment] 2019-08-03 21:27
Ouch! Sorry about that. I will look into this and update asap.

**Comment by keepassium** [comment] 2019-08-03 21:47
Bug confirmed, caused by too aggressive [memory clean up](https://github.com/keepassium/KeePassium/blob/8e00de1a340c5c937fad9aa53aefb9bee4d16a1d/KeePassiumLib/KeePassiumLib/db/kp2/Entry2.swift#L170). Will be fixed in the next update, as soon as possible.

**Closed** 2019-08-12 19:59 UTC
Labels: bug
