### ISSUE TITLE
Cant fill in any password in Safari

### ISSUE THREAD

**Issue by Fischmuetze** [keepassium/KeePassium#374] opened 2024-07-05 16:45 UTC
KeePassium is configured for password management
I can select KeePassium in a password field as password supplier
I can login in the KeePassium password db
I can select an Item 
but the password will not filled in in the password field of the website

**Expected behavior**
Put the password of the selected entry in the password field of the website

**Environment:**
macOS Sonoma 17.5, 
Safari 17.5 (19618.2.12.11.6)

**Comment by Fischmuetze** [comment] 2024-07-05 19:58
this seems to be affected to single field forms like the Fritzbox Login page

**Comment by keepassium** [comment] 2024-07-05 22:13
Unfortunately, this is a system issue. Closing as duplicate of https://github.com/keepassium/KeePassium/issues/259

**Closed by keepassium** 2024-07-05 22:13 UTC
Labels: bug
