### ISSUE TITLE
Manual TOTP setup

### ISSUE THREAD

**Issue by ghost** [keepassium/KeePassium#153] opened 2021-03-26 16:01 UTC
**Describe the feature you'd like**
Hello I immediately noticed as a user that the TOTP setup in KeePassium is very cumbersome and you don't immediately know how to set it up in KeePassium.

It is not designed in a user-friendly way, only by searching the internet search later did I find out how it works on your website. I find it very poorly designed.

I think it's better if an app is designed in such a way that it works immediately at first sight or through logical behaviour in the UI.

In this case, that means adding a setup for TOTP. Under entry "TOTP setup" button should be added, when user clicks on it he can set the time (by default it uses the default values) and can simply insert the key in field and click "OK", then it is set up immediately in 3 steps.

**Comment by keepassium** [comment] 2021-03-26 18:16
Thank you for the suggestion. This seems duplicate of #24, which has been implemented in v1.22.84 (already in the AppStore).

**Comment by keepassium** [comment] 2021-03-26 18:20
On a closer look, you focus mainly on manual setup, whereas #24 is QR-code based. 

However, I believe QR-scanning procedure covers 95% of use cases. Someone who prefers manual setup would not mind entering code parameters manually as well.

**Comment by Guntriaske457** [comment] 2021-03-27 00:05
> However, I believe QR-scanning procedure covers 95% of use cases. Someone who prefers manual setup would not mind entering code parameters manually as well.

I don't like apps that manually enter the code parameters, I didn't even know how to do that, it only worked because you have a screenshot on your website. It took me several minutes until it worked.

My suggestion was to do it in 3 steps and that would work immediately and the user only has to enter the key manually and click OK.

QR code I do not use, because of camera access or for other reasons, such as the QR code cannot be scanned due to lack of light or the camera is broken.

The report should be reopened, because would like to set up TOTP without entering code parameters manually for each entry. This is very time consuming and requires too many steps. The report here is actually to speed up the manual setup so to improve it.

**Comment by keepassium** [comment] 2021-03-27 10:15
> the user only has to enter the key manually

> set up TOTP without entering code parameters manually

I guess I am missing something, because this is confusing. Without QR code, the only way to enter code parameters is manually. 

Or do you mean adding some UI that would show separate fields for code parameters, so the user does not have to create these fields manually as well?

**Comment by Guntriaske457** [comment] 2021-03-27 15:52
> Or do you mean adding some UI that would show separate fields for code parameters, so the user does not have to create these fields manually as well?

Yes, I don't want to enter the code parameters manually every time for each entry.

But I just want to insert my key in the field and click OK and it will show me TOTP code.

**Comment by Guntriaske457** [comment] 2021-03-27 16:12
An example with the key is here on github, you can copy the key manually so without using QR code and then paste it into the field where the code parameters are.

https://github.com/settings/two_factor_authentication/verify? -> **enter this text code**

But I want the code parameters to be already in entry automatically and enabled by default, so I don't have to set it up myself every time.

This is how I imagine it
1. Open Safari iOS -> https://github.com/settings/two_factor_authentication/verify? -> **enter this text code** -> copy the code to the clipboard or enter it manually (without the clipboard)
2.  Open KeePassium -> create new Entry -> paste the key from the clipboard or enter it manually into the TOTP field and you're done. The code parameters are automatically already created when the user creates a new entry.

As an alternative it would also be possible if I create a new entry I still have to manually click on TOTP setup button. then everything is automatically set up with one click and can then paste the key from the clipboard. As you can see I don't have to add the code parameters manually, for the users who want to add code parameters manually can do it as before, this function remains.

**Comment by keepassium** [comment] 2021-03-28 11:36
Thank you for clarifying, @Guntriaske457! 
I have reopened the feature request, so it is on the list. But it might take some time to get to it, depending on demand.

**Comment by virtualize** [comment] 2022-01-05 18:39
I too would like to see an easier way to manually add TOTPs. It's more relevant in the macOS version where you can not scan QR codes that are displayed on the screen.

It also took me a while to find your guide: https://keepassium.com/articles/how-to-setup-totp/

**Comment by keepassium** [comment] 2023-09-05 08:48
Has been done in 82a41c79136ab234ea39a06e16ad135a9f99f4da and released in v1.43.130.

**Closed by keepassium** 2023-09-05 08:48 UTC
Labels: enhancement
