### ISSUE TITLE
AutoFill errors when adding database if iCloud Drive is disabled

### ISSUE THREAD

**Issue by Nu11u5** [keepassium/KeePassium#96] opened 2020-04-25 23:00 UTC
**Describe the bug**

If the iCloud Drive service for the user's AppleID is disabled, then when the KeePassium AutoFill is opened and the user taps to add a database the app displays "Something went wrong while displaying documents".  This error does not happen in the main app.  It does not matter what the last Files Picker location was, or what other Files services are enabled.

**To Reproduce**

1. In "Settings > AppleID > iCloud" disable "iCloud Drive"
2. Open any app or website that will present password autofill
3. Use a password field to invoke KeePassium AutoFill
4. Navigate to the Databases screen
5. Tap "+" to add a database
6. Observe the "Something went wrong..." error
7. In "Settings > AppleID > iCloud" *re-enable* "iCloud Drive"
8. Repeat steps 2-5
9. Observe that the error is gone, and the Files Picker appears

**Expected behavior**

The Files Picker appears after tapping "+" on the Databases screen instead of the "Something went wrong..." error message.

**User Information (please complete the following information):**

 - Device: iPhone 8
 - OS: 13.4.1
 - App Version: 1.11 beta

**Comment by keepassium** [comment] 2020-04-25 23:11
Wow! You have just solved the mystery around #79. This is a huge relief, thank you very much!

This looks like an iOS issue to me... I will play around with the file picker parameters, in case I'm missing something. If unsuccessful, I'll submit this to Apple.

**Comment by keepassium** [comment] 2020-04-26 10:26
An important detail: iCloud Drive should also be enabled in the Files app (Files → `...` → Edit → iCloud Drive). Thanks to JPP for finding & sharing this.

**Comment by SteffKirch** [comment] 2020-08-17 10:23
I have the same problem - BUT the workaround doesn' work. independently if I enable or disable iCloudDrive (in the system and in the app), I still got the error. I also tried to create a keepass-database on iCloud-Drive and opend this as the last database in Keepass - without any effort. Also changing the iOS-Language to english - no effort.
Any idea?

**Comment by SteffKirch** [comment] 2020-08-17 13:59
Is it possible, that my problem has something to do with the "Recents"? After upgrading my iphone, I had some "old" databases in the AutoFill-Area and deleted them all. And now, I have the problem - perhaps there some old (and non existing values) in "Recents" which lead the app to a non-existing directory so the "try again"-error occurs? Any idea, how to clear the Recents (it seems to be "another" recents as in the Keepass-App itself).

**Comment by keepassium** [comment] 2020-08-17 23:32
@SteffKirch, unfortunately, I don't have a useful answer: so far, this workaround has always worked... 

> After upgrading my iphone, I had some "old" databases in the AutoFill-Area and deleted them all.

Since you mentioned an upgrade... Which iOS version do you have?

> Any idea, how to clear the Recents (it seems to be "another" recents as in the Keepass-App itself).

Do you mean you can open the "Recents" tab in the file picker dialog in AutoFill?

**Comment by SteffKirch** [comment] 2020-08-18 11:26
I changed my iPhone from XS to 11Pro - and in this context, I upgraded to 13.6.1 - But: as I mentioned, it worked fine at the beginning. but since that time, I deleted *all* databases in the autofill-context, I got this "Try again" error.

And no - I don't see any "Recents" tab - I just compare the behaviour to other iOS-Devices and have the feeling, that this could be the reason.

**Comment by keepassium** [comment] 2020-08-18 14:04
> it worked fine at the beginning. but since that time, I deleted all databases in the autofill-context, I got this "Try again" error.

The file selection dialog is managed by the system, it is completely separate from the databases in AutoFill... 

Did you try to restart the device?

**Comment by SteffKirch** [comment] 2020-08-18 14:27
We also checked the code in github and have no idea. 

Yes, I restarted the iphone several times, without any effort.

BUT: On my iPad, I have the same problem, when pressing [+] - I just don't tried that, because my favorite databases is allready there. I also tried reinstalling the App without licensining the premium-version and so on. Tomorrow, I will try to check this behaviour on another completly new installed iPhone with my iCloud-Account. Perhaps, the problem is in my iCloud-Account itself?!?

**Comment by SteffKirch** [comment] 2020-08-19 12:59
Hmm - I tried to reproduce the error on a new iphone - which I don't restore of a backup - but everything works fine - same iCloud-Account and so on.
So I still have the feeling, that perhaps somewhere in the system there is a entry for the last used directory in the "Autofill / Add database", which initializes the file-picker and because of the restore, this directory is a non existing directory (e.g. the "old" local iPhone or something similar).

Is there a possibility, to add a database directly in the system or change the directory?

**Comment by keepassium** [comment] 2020-08-20 15:02
I agree, this might be something about the initial state of the file picker (default directory, or recent files, or something else). It seems that file picker [allows](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller/3183918-directoryurl) setting the initial directory. I will give it a try tonight.

In the meanwhile, you can use a workaround:
- [Update](https://support.apple.com/en-us/HT202180#manual) to the latest release (1.14.69)
- Open your database in the main app. Every time you open or save the database, KeePassium will update its latest backup copy (DatabaseName_latest.kdbx). 
- Open app settings → Database backup → Show backup files → turn on. 

Now when you open AutoFill, you can open the latest backup of your database. It's a local file and will appear automatically, no need to add anything.

**Comment by keepassium** [comment] 2020-08-20 15:20
Nope, the initial directory has no effect. Yes, the file picker seems to open the last-used directory. But if I leave it on Dropbox, then disable Dropbox in the Files app, then try again the AutoFill file picker — it simply switches to iCloud Drive instead. 

So everything points to iCloud Drive. It should be enabled both in the system settings and in the Files app. Otherwise, I'm out of ideas for now...

**Comment by carlin-q-scott** [comment] 2020-08-23 19:37
@keepassium can you provide an error message stating that we need iCloud enabled? That would have saved me from half an hour of failed solution beforeI found this big report.

**Comment by keepassium** [comment] 2020-08-23 22:21
@carlin-q-scott, I would be happy to, but I don't think KeePassium can detect there was an error. Since the file picker is managed by the system, KeePassium can only detect that the user did not select a file. 

Well, maybe the AutoFill could show a subtle popup like "Could not select the file? [Read more]" and show the solution. I'll add this to my list. Thanks for the suggestion!

**Comment by SteffKirch** [comment] 2020-09-23 19:15
After upgrading zu iOS14 everything works fine, so it really seems to be a bug in iOS13.

**Comment by keepassium** [comment] 2020-09-23 21:03
@SteffKirch, this is great to know, thanks for reporting!

So I will (happily) close the issue, then :)

**Closed by keepassium** 2020-09-23 21:03 UTC
Labels: bug
