### ISSUE TITLE
Cannot add database to AutoFill

### ISSUE THREAD

**Issue by thettenhausen** [keepassium/KeePassium#112] opened 2020-07-10 09:43 UTC
When I am trying to use the AutoFill feature I am getting the error that the database cannot be added and that I should retry, without any success.

1. Go to any website with forms
2. Try to use the autofill feature (click form field, click key symbol, select KeePassium, click "add database" button

Expected behavior
Database can be added to AutoFill "version" of KeyPassium

User Information (please complete the following information):
 - Device: iPhone Xs 64GB
 - iOS: 13.5.1 (German)
 - App Version: 1.13.62

I was just seeing if it was fixed after never really bothering in the last months, decided to google, found info it was fixed in 1.09, and checked again... no luck for me though. Otherwise working great though!

**Comment by thettenhausen** [comment] 2020-07-10 09:45
Just to add: in Settings I have enabled KeePassium as an Autofill provider.

**Comment by keepassium** [comment] 2020-07-10 11:37
Hi, thanks for the feedback!

It seems you refer to two different problems simultaneously, so I'm a bit confused...

The title refers to the [AutoFill Face ID loop bug](https://github.com/keepassium/KeePassium/issues/74) which was indeed addressed in 1.09. If you still get repeating Face ID prompts, can you please tell me your App Lock timeout? (settings → App Protection → Timeout).

The steps to reproduce, in contrast, refer to an error message when adding a database to AutoFill. This sounds very similar to #96. If so, please check the workaround mentioned there and let me know if the issue remains. Thanks!

**Comment by thettenhausen** [comment] 2020-07-10 11:51
Hi, 
Thanks for answering. I am not sure why you say this is two issues? I got the problem description from what I saw in the log, so maybe there is the confusion - sorry if I mixed it up.

I tried the workaround and first disabled and then re-enabled iCloud Drive and trying to add a database to KeePassium both with iCloud disabled and then re-enabled. Same bug unfortunately.

The 

-0.000 (W) 	SystemIssueDetector.swift:39 	scanForIssues() 	Detected a known system issue: autoFillFaceIDLoop_iOS_13_1_3
0.000 (I) 	MainCoordinator.swift:54 	init(rootController:) 	KeePassium AutoFill v1.13.62 (iPhone, iOS 13.5.1)
0.598 (I) 	PremiumManager.swift:214 	updateStatus(allowSubscriptionExpiration:) 	Premium subscription status changed [was: initialGracePeriod, now: freeLightUse]
0.599 (I) 	Watchdog.swift:248 	engageAppLock() 	Engaging App Lock
0.634 (D) 	MainCoordinator.swift:828 	showBiometricAuth() 	Biometric auth: showing request
0.643 (D) 	FileKeeper.swift:827 	deleteExpiredBackupFiles() 	Will perform backup maintenance
0.653 (I) 	FileKeeper.swift:829 	deleteExpiredBackupFiles() 	Backup maintenance completed [allOK: true]
1.142 (I) 	MainCoordinator.swift:833 	showBiometricAuth() 	Biometric auth successful

**Comment by thettenhausen** [comment] 2020-07-10 11:56
Not sure how I closed this, was copying the diagnostic protocol on the phone, must have hit some button accidentally, sorry. That is also why the sentence stops directly after "The"... - it should read:

The diagnostic protocol looks like this, and this is where I got the description for the description.

Additionally, the lockout is probably set to instantly. In German I have something I'd translate back as "Waiting time" under "Access Protection". That is set to "Instantly, upon leaving app".

Might this also be related to being on Free? As in: only having one DB in the App, so only in normal mode, none possible in Autofill mode?

**Comment by keepassium** [comment] 2020-07-10 12:11
Ah, well, the Face ID issue in the log is unrelated to adding the database. 

Is this the error you see?

![IMG_4321](https://user-images.githubusercontent.com/38399598/87152355-d6647b80-c2b5-11ea-85b4-e2470cb89848.PNG)

> KeePassium AutoFill
> Something went wrong while displaying documents.
> Try again

> KeePassium: automatisches Ausfüllen
> Beim Anzeigen von Dokumenten ist ein Fahler aufgetreten.
> Wiederholen

**Comment by thettenhausen** [comment] 2020-07-10 12:17
Yes, exactly.

**Comment by keepassium** [comment] 2020-07-10 12:31
> Yes, exactly.

In this case, this is a duplicate of #96. The workaround involves two steps (enable iCloud Drive in system settings [and](https://github.com/keepassium/KeePassium/issues/96#issuecomment-619524924) make it visible in the Files app), so make sure to check them both.

**Closed by keepassium** 2020-07-10 12:31 UTC
Labels: bug

**Comment by thettenhausen** [comment] 2020-07-10 12:53
Youe are right. I did not see your later comment there about enabling iCloud Drive in Files. Now it works. Thanks!
