### ISSUE TITLE
Occasionally freezes when accessing local files on iOS 13

### ISSUE THREAD

**Issue by loblawbob** [keepassium/KeePassium#71] opened 2019-10-24 20:25 UTC
**Describe the bug**
I can start the app after a fresh install. As soon as I add a database file (in this case iTunes file transfer) all I get when starting is a white splash screen that stays for a while until it returns to the home screen. Adding a file while KeePassium is running will stop execution when refreshing the list of databases until crash to home screen.

Creating a new database will stay on the "Saving..." screen where I can take no further action. After a while it returns to the creation dialog which is unresponsive. When I restart the splash screen bug occurs.

I tried this with my regular DB and a newly created DB with just the sample entries.

I had this bug for a while and sometimes the app would start for some reason and I was able to use it. It was somehow linked to the process of adding the DB to auto fill. An earlier version was working without problem.

Can I provide any other information which might help with fixing?

**To Reproduce**
1. Install app
2. Add database file
3. Open app

Having openend the app first makes no difference.

**Expected behavior**
Database appears in list and can be opened.

**User Information (please complete the following information):**
 - Device: iPhone 6s Plus
 - OS: iOS 13.1.3
 - App Version: newest as of 24.10.2019

**Comment by keepassium** [comment] 2019-10-24 21:14
Hi, thank you for the report! 

Looks like another iOS 13 heisenbug... My dev phone (iPhone SE) is also running 13.1.3, but I cannot reproduce this. (I have just installed the latest v1.06.42 from the App Store, then copied a database to KeePassium via iTunes, then opened KeePassium. The app launched and showed the database in the list...)

Can you check if there is a crash log in phone's settings — `Privacy` — `Analytics` — `Analytics Data`? The log should be named either "KeePassium" or "JetsamEvent" with a suitable timestamp. If you could email the crash log to me, that would be very helpful. Thanks!

**Comment by keepassium** [comment] 2019-10-26 19:37
@loblawbob, thanks again for the crash logs! 

Here's the relevant part:

    Exception Type:  EXC_CRASH (SIGKILL)
    Exception Codes: 0x0000000000000000, 0x0000000000000000
    Exception Note:  EXC_CORPSE_NOTIFY
    Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
    Termination Description: SPRINGBOARD, scene-create watchdog transgression: application<com.keepassium.ios>:9026 exhausted real (wall clock) time allowance of 19.98 seconds | ProcessVisibility: Background | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 16.270 (user 16.270, system 0.000), 41% CPU", | "Elapsed application CPU time (seconds): 0.126, 0% CPU" | )
    Triggered by Thread:  0
    
    Thread 0 name:  Dispatch queue: com.apple.main-thread
    Thread 0 Crashed:
    0   libsystem_kernel.dylib    __ulock_wait + 8
    1   libdispatch.dylib         _dlock_wait + 52
    2   libdispatch.dylib         _dispatch_group_wait_slow + 52
    3   CoreServicesInternal      createBookmarkWithURLAtDepth+ 23128 (__CFAllocator const*, __CFURL const*, unsigned long, __CFURL const*, __CFArray const*, BookmarkMutableData&, unsigned int, bool, __CFError**) + 3828
    4   CoreServicesInternal      _CFURLCreateBookmarkData + 328
    5   CoreFoundation            -[NSURL bookmarkDataWithOptions:includingResourceValuesForKeys:relativeToURL:error:] + 160
    6   libswiftFoundation.dylib  URL.bookmarkData+ 910312 (options:includingResourceValuesForKeys:relativeTo:) + 216
    7   KeePassiumLib             URLReference.init(from:location:) + 604300 (URLReference.swift:110)
    8   KeePassiumLib             FileKeeper.scanLocalDirectory(_:fileType:) + 543816 (URLReference.swift:0)
    9   KeePassiumLib             FileKeeper.getAllReferences(fileType:includeBackup:) + 541956 (FileKeeper.swift:283)
    10  KeePassium                ChooseDatabaseVC.refresh() + 396672 (ChooseDatabaseVC.swift:146)    


What happens is: 

- The app looks for local databases inside the sandbox (`FileKeeper.scanLocalDirectory()`);
- For each database, it tries to create a reference/bookmark (`URLReference.init()`);
- This call successfully propagates to the system core services...
- ...until it gets stuck in the kernel's (`__ulock_wait`) waiting for something (a deadlock?);
- After 19.98 seconds, another part of the system kills the app as unresponsive ("application<com.keepassium.ios>:9026 exhausted real (wall clock) time allowance of 19.98 seconds").

So the culprit seems to be `createBookmarkWithURLAtDepth` that does not return neither a bookmark nor an error, and instead just hangs. I guess, this is yet another iOS 13 bug that will hopefully be fixed in iOS 13.2...

**Comment by loblawbob** [comment] 2019-10-28 19:06
13.2 has indeed fixed this issue for me. Thanks for your detailed response!

**Comment by keepassium** [comment] 2019-10-28 21:07
That’s a relief :) Thank you for the update!

**Comment by loblawbob** [comment] 2019-11-17 22:04
v1.07.43 has re-introduced this issue for me. I have sent you another crash log from just now.

**Comment by keepassium** [comment] 2019-11-18 22:16
@loblawbob, thanks for the crash log! 

Unfortunately, the crash reason is the same as before: when the app tries to create references to its local files, it gets stuck deep in the system and then killed by a watchdog.

1. Do you have Touch ID enabled in the app? If yes, please disable it and check if the issue persists. A [vaguely related report](https://forums.developer.apple.com/message/384064#thread-post-387597) suggests that it might be related to accessing files while the app is transitioning to foreground state.
2. Does the phone have any remove administration software installed (MDM, mobile device management)? I'm asking just in case there is a company's IT policy that might be interfering with file access (like in [that case](https://www.reddit.com/r/KeePassium/comments/dwp9r1/keepassium_cant_seem_to_open_keepass_243_kdbx/f7nrs82/)).
3. The issue seems to be related to the iOS version (iOS 13.2.2 now), rather than the app. But just to be sure, can you please install the beta version (following [these instructions](https://keepassium.com/beta)), then roll back to the previous version (TestFlight app — KeePassium — Previous Builds — 1.06 — Install 1.06 (42). Does the crash still happen?

Thank you for your help!

**Comment by loblawbob** [comment] 2019-11-19 08:02
I‘m not at my computer right now so I tested not by adding a file through iTunes but from the files app (in KeePass  in the database info panel it then says that it is saved elsewhere) and through the add database dialog in KeePass (from there also selecting from the files app). And now this bug does not occur and everything works fine.

I can check more later with iTunes again to see if it really is the culprit and test with the older version and TouchID disabled (I don‘t have any MDM policies).

**Comment by loblawbob** [comment] 2019-11-19 17:49
I can't replicate this at all now. I reinstalled somewhere along the way and now everything works just fine.

**Comment by keepassium** [comment] 2019-11-19 19:52
If this happens again, feel free to reopen. Hopefully, we'll figure out the pattern eventually.

**Comment by keepassium** [comment] 2019-12-14 22:19
This is reported to happen (sporadically) also on 13.2.3 and 13.3 [thanks, J.K.]

I'm also observing this on 13.2.3 with databases accessed via Nextcloud and DS file apps.

**Comment by keepassium** [comment] 2020-01-19 15:30
This should be fixed for local files now (completely avoiding the URL.bookmarkData() call whenever possible). Will reopen if this happens again.

**Closed by keepassium** 2020-01-19 15:30 UTC
Labels: bug
