### ISSUE TITLE
Enhance Password Generator features

### ISSUE THREAD

**Issue by FlightMS** [keepassium/KeePassium#160] opened 2021-05-02 14:07 UTC
I would like to generate phonetic passwords with the Password Generator as they are also more secure than „normal“ passwords and easier to remember.

Also it would be nice if the Password Generator is more present than now. When I want to create a new password, I have to create a new entry or edit an existing one.

**Comment by keepassium** [comment] 2021-05-02 14:25
Thanks! These are good suggestions, and they are already in the queue.

> I would like to generate phonetic passwords with the Password Generator as they are also more secure than „normal“ passwords and easier to remember.

If by phonetic you mean passphrases like Diceware, this is already in list (#78)

> Also it would be nice if the Password Generator is more present than now. When I want to create a new password, I have to create a new entry or edit an existing one.

This seems like a duplicate of #155...

**Comment by FlightMS** [comment] 2021-05-02 14:34
With phonetic i thought about this: https://help.passwordsafe.de/v8/1/en/topic/passwortgenerator
But it sounds like that it‘s working the same way like Diceware..

And the second point seems like a duplicate of the other issue, I can confirm that!

**Comment by keepassium** [comment] 2021-05-02 20:07
Thanks! I'll consider this for the new password generator UI.

**Closed** 2022-05-29 12:09 UTC
Labels: enhancement
