### ISSUE TITLE
Synology drive compatibility 

### ISSUE THREAD

**Issue by axgdcode** [keepassium/KeePassium#292] opened 2023-05-08 10:32 UTC
I would like the application to be compatible with the Synology Drive application. https://www.synology.com/fr-fr/dsm/feature/drive

Drive appears in iOS today but, it's impossible to access the kdbx file from keepassium

**Comment by keepassium** [comment] 2023-05-08 10:35
It is already compatible: https://keepassium.com/articles/sync-ios-keepass-with-synology-nas/

> it's impossible to access the kdbx file from keepassium

Can you elaborate on this, please? Are there any error messages?

**Comment by axgdcode** [comment] 2023-05-08 11:17
sorry I didn't find this issue.
The kdbx is visible but impossible to open (waiting message for accessing the file...)
![signal-2023-05-08-12-14-19-390](https://user-images.githubusercontent.com/1721781/236810310-3ee6f8cf-2584-4eae-8198-2fdaad58044d.png)

**Comment by keepassium** [comment] 2023-06-07 18:02
Closing, since the issue is unrelated to KeePassium.

**Closed by keepassium** 2023-06-07 18:02 UTC
Labels: enhancement
