### ISSUE TITLE
App switching using gestures randomly caused Keepassium to stop displaying the text in entries until full app reinstall.

### ISSUE THREAD

**Issue by martinsstuff** [keepassium/KeePassium#151] opened 2021-03-17 09:00 UTC
**Description**
The text in the main page of entries is invisible, text in other areas appears correctly. Using the "edit" button of an entry can be a way of still accessing the information if reinstalling isn't an option (i.e. bug is only visual, actual entries don't seem to be affected, though I haven't tried modifying anything in this state).

**How to reproduce**
??? Unknown ???

I often use gestures to swap between Keepassium and an app or browser where I enter a password and never had any issues, this time it completely broke the app.

**Expected behavior**
Not this

**Screenshots**
https://i.imgur.com/DQuUduI.mp4

https://i.imgur.com/49fTwlb.mp4

Second video pictures tap copying and attempting to make the password visible.

Note: Both entries had a username and password set. 

**Environment:**
 - Device: [e.g. iPhone 12] **iPad 6th Generation**
 - OS: [e.g. iOS14.4] **14.4.1**
 - App Version: [e.g. 1.23.45] **v1.21.81**

**Additional context**
I tried restarting the app, removing and adding the database and restarting the iPad, ultimately only deleting and reinstalling the app solved the issue.

**Comment by martinsstuff** [comment] 2021-03-17 09:09
While I don't know what caused this exactly, for all I know it may have been some cosmic ray bitflip, the big issue is definitely that this bugged state is able to persist across app and system reboots.

**Comment by keepassium** [comment] 2021-03-17 10:07
Thank you for the feedback! 

This issue looks very similar to #132. Apparently, there was a bug in pinch-to-zoom text resizing, so the text disappeared for all kinds of wrong reasons (including a [cat](https://www.reddit.com/r/KeePassium/comments/k7b2zp/did_my_cat_blow_up_my_keepassium_on_my_ipad/)). In the current [beta](https://keepassium.com/beta), I have disabled the gesture and moved text size to the settings (should be easier to find, too). So starting from the next release, the issue should not happen again.

In the meanwhile, there is a workaround: at the end of the "About" screen, there is a "Reset entry text size to default" — it should fix the problem.

(I will close it as a duplicate of #132. Unless the issue repeats in the upcoming v1.22, of course.)

**Closed** 2021-03-17 10:07 UTC
Labels: bug, duplicate
