### ISSUE TITLE
App screen is not reliably hidden in app switcher

### ISSUE THREAD

**Issue by bob-lobster** [keepassium/KeePassium#330] opened 2023-11-17 11:24 UTC
**Description**
Closing the app will sometimes, especially when closing the app right after unlocking through FaceID, not show the splash in the app switcher, possibly leaking database details including shown passwords. Instead the last seen view will show and can then be seen in the app switcher.

**How to reproduce**
1. Open app
2. Close app immediately after FaceID prompt
3. Open app switcher
4. See last view of app instead of splash screen

**Expected behavior**
Only the splash screen is shown in the switcher, hiding any app details.

**Screenshots**
![IMG_2808](https://github.com/keepassium/KeePassium/assets/86841355/6deabcce-4aea-4756-b6ba-910ffccac0e0)

**Environment:**
 - Device: iPhone 13 Pro
 - OS: iOS 17.1.1
 - App Version: 1.46.140

**Comment by keepassium** [comment] 2023-11-22 23:08
Thank you for the feedback!

> Closing the app will sometimes, especially when closing the app right after unlocking through FaceID, not show the splash

Just to be sure: is it "especially" or "only"? 

I can confirm the "only" case: if the app is minimized during Face ID animation, the UI might appear uncovered. This is due to a technical challenge:
- Face ID prompt appears as a separate system-controlled window above KeePassium. 
- When it appears, the system notifies the app that it was just sent to background/minimized.
- After a successful Face ID scan, the system notifies the app about success, but still shows Face ID animation for 1-2 seconds (depending on device).
- During this time, the app is in a limbo state: it already knows Face ID was successful, but the app is still "in background". 
- Unlocking the app immediately proved to be a bad idea: once Face ID animation finishes and KeePassium becomes the "foreground" app, it would detect that was just switched to and needs to lock up. This causes [Face ID prompts to appear repeatedly](https://github.com/keepassium/KeePassium/issues/266).
- To work around this issue, the app delays unlocking by a second (or two). This prevents racing conflicts between Face ID notifications and app state transitions.

But as a side effect, if you minimize the app during Face ID animation, the app switcher screenshot might indeed catch the app unlocked after the Face ID delay. The best solution I can offer at the moment is to avoid minimizing the app during Face ID animation... (aka "just avoid holding it in that way".)

Have you noticed other scenarios where the issue occurs?

**Comment by keepassium** [comment] 2023-12-21 22:15
@bob-lobster , any feedback on the questions above?

**Comment by bob-lobster** [comment] 2023-12-21 23:11
Thanks for your reply and sorry for not getting back directly.

I indeed can‘t replicate it in any other scenario.

I have tried replicating it in other apps though.

In my banking app it never happens. In Microsoft Authenticator it is harder to replicate but can happen with the right timing.

Since it is a niche scenario I agree it can be worked around.

**Comment by keepassium** [comment] 2023-12-22 16:07
Thank you for the update. In this case I will close this as a known limitation.

**Closed by keepassium** 2023-12-22 16:07 UTC
Labels: bug
