### ISSUE TITLE
Add OTP by image of QR code or paste

### ISSUE THREAD

**Issue by coughingmouse** [keepassium/KeePassium#290] opened 2023-04-20 06:20 UTC
Adding OTP from an app on the phone is impossible because I can only take photo of a qr code. I wish I can add it without a second phone.

**Comment by keepassium** [comment] 2023-04-20 06:27
Closing as duplicate of #153. 
In the meanwhile, you can add the code manually as described here: https://keepassium.com/articles/how-to-setup-totp/

**Closed by keepassium** 2023-04-20 06:27 UTC
Labels: duplicate, enhancement
