### ISSUE TITLE
Dropbox sync issues

### ISSUE THREAD

**Issue by DannieBGoode** [keepassium/KeePassium#344] opened 2024-02-21 11:21 UTC
My Keepassium app on my iPhone syncs from dropbox, I followed the guide in which you need to have the dropbox iOS app downloaded and enabled in the Files App.

However, any time I modify the KeePass database no my desktop, I need to manually open the Files application my iPhone for the file to sync, if not KeePassium keeps using the older version of the database which can lead to conflicts down the line.

I see two possible solutions here:
* Is there a way to force background dropbox folder sync on iOS without manually opening the Files App and navigating to the folder you want to sync?
* Has KeePassium considered a WebDAV integration with Dropbox like the competition such as Strongbox does? This works very well.

**Comment by keepassium** [comment] 2024-02-21 11:44
Thank you, @DannieBGoode. This sounds like a duplicate of #340, which covers both questions :)

**Closed** 2024-03-06 13:09 UTC
Labels: duplicate, refinement
