### ISSUE TITLE
Save multiple websites per entry

### ISSUE THREAD

**Issue by Ironwally** [keepassium/KeePassium#389] opened 2024-09-30 08:38 UTC
**Describe the feature you'd like**
Save multiple websites per entry for auto fill.

And *why* you need it — that is, how it would make your life better.

Some websites have different addresses, but take same password, username combination. 
- Autofill work with multiple websites.

**Comment by keepassium** [comment] 2024-09-30 09:09
Thank you! Looks like duplicate of #180

**Closed by keepassium** 2024-09-30 09:09 UTC
Labels: enhancement
