### ISSUE TITLE
iOS Dark Mode Issue

### ISSUE THREAD

**Issue by shad0whawk** [keepassium/KeePassium#56] opened 2019-09-15 03:49 UTC
**Describe the bug**
I’m not sure where you’re at in the process of supporting dark mode, but I wanted to let you know that the application doesn’t look good in dark mode.  I opened the application this evening and dark mode was automatically enabled within KeePassium because my system settings are set to switch between light mode and dark mode depending on time of day.  I noticed that most of the text was impossible to read and there were a lot of inconsistencies between screens and parts of the screen. By the looks of it you haven’t gotten to far in the process, but I thought I’d open an issue anyways and attach some screenshots to show you what I’m saying.

**To Reproduce**
1. Enable dark mode
2. Open KeePassium 

**Expected behavior**
I expected it to look readable and consistent. I think if dark mode support isn’t ready within the application then it should default to light mode until it is.

**Screenshots**
Attached

**User Information (please complete the following information):**
 - Device: XS Max
 - OS: iOS 13.1 beta 3
 - App Version: 1.02.34.

**Comment by shad0whawk** [comment] 2019-09-15 03:50
![5FC4A1EB-1C08-4D86-B288-4D614FB5A8C9](https://user-images.githubusercontent.com/6074105/64916347-94bc8000-d739-11e9-8d82-ef72cb9c9a2e.png)
![F6200F30-3CE3-4883-AB3B-08EC30A045E3](https://user-images.githubusercontent.com/6074105/64916348-94bc8000-d739-11e9-83b8-fff448e82994.png)
![476B1BCF-64C8-4D79-BC55-69410EC3E686](https://user-images.githubusercontent.com/6074105/64916349-94bc8000-d739-11e9-9d94-384fd08990ce.png)
![21B31F2B-8D9D-44AC-9C4D-CFB516450F9C](https://user-images.githubusercontent.com/6074105/64916350-95551680-d739-11e9-9810-272ce27104b8.png)

**Comment by keepassium** [comment] 2019-09-15 13:16
Thanks for the screenshots!

Yes, I am in the process of adopting iOS 13 (half of the [changes in v1.02.34]((https://github.com/keepassium/KeePassium/commit/7ec2c7200db384d944a212a6c87dc5dd2891c720)) are iOS13-related fixes). 

The dark mode is already on my list (#35). For some reason, I thought that the dark mode support is an opt-in process (that is, the system by default assumes the app supports only the light mode). Apparently, it's the other way round: the system assumes the app supports both modes, unless the app declares otherwise. 

I will try to add the dark mode support as quickly as possible (#35). If it takes more than a couple of days, I will tell the system that KeePassium supports only the light mode — as a temporary workaround, while the #35 is in progress.

**Comment by keepassium** [comment] 2019-09-17 21:42
I've just added dark mode support in v1.02.35 (and referenced a wrong issue in the commit message).

Please check how it looks now and post any bugs here. Thanks!

**Comment by shad0whawk** [comment] 2019-09-17 21:44
Dark mode looks good so far but the Preferences text strings aren’t displaying correctly in either mode. 
![F56CD105-1986-491C-8AAB-8ECA0126D424](https://user-images.githubusercontent.com/6074105/65081931-f7906000-d961-11e9-8311-aa5515497753.png)

**Comment by shad0whawk** [comment] 2019-09-17 21:46
And in the attached files window
![628E756D-B926-4C54-8E44-769893091676](https://user-images.githubusercontent.com/6074105/65082034-358d8400-d962-11e9-82ae-10f79102bde0.png)

**Comment by shad0whawk** [comment] 2019-09-17 21:49
This is also the case on some of the Preferences menu sub items. I can open a separate issue if needed.

**Comment by keepassium** [comment] 2019-09-17 21:51
It's a regression caused by the workaround for #60... I thoroughly tested it in several locales, except the base one.

**Comment by shad0whawk** [comment] 2019-09-17 23:21
I see you fixed in the latest release (.36) but the text sizes in the preferences menu are inconsistent—some use a bigger font and others a smaller font. I’m assuming this is not by design.

**Comment by keepassium** [comment] 2019-09-17 23:26
Destructive buttons are a bit smaller, the other labels should have the same font. Can you upload a screenshot?

**Comment by shad0whawk** [comment] 2019-09-17 23:37
Start with Search is smaller than the rest in one. Timeout is larger than the rest. There are other screens with this mixture that I didn’t include in screen shots. If by design than disregard my comment—just looks a bit funny mixing the sizes. 
![F984600E-5EE1-47C4-BA67-C1C60E12D70D](https://user-images.githubusercontent.com/6074105/65087048-67f2ad80-d971-11e9-8fea-0203fa79017e.png)
![91E98CA2-CC20-42AE-8B6C-806CA18BE71E](https://user-images.githubusercontent.com/6074105/65087049-688b4400-d971-11e9-92ac-bd2140879c47.png)

**Comment by keepassium** [comment] 2019-09-17 23:48
Wow, that looks wrong! It's not by design.

I checked in iOS 13 simulator and on device (iPhone SE) — everything seems fine here... I will look into this. Thanks for the screenshots!

**Comment by shad0whawk** [comment] 2019-09-17 23:52
Didn’t think so :-) if it helps, this is on both an iPhone 8 and XSMax running iOS 13.1 beta 3.

**Comment by keepassium** [comment] 2019-09-18 06:26
Uh, ok. Then it can as well be Apple’s beta bug...

Does anyone have the font size issue on iOS 13.0?

**Comment by shad0whawk** [comment] 2019-09-18 18:34
True it could be. Updated to iOS 13.1 beta 4 today and it persists.

**Comment by ankurkotwal** [comment] 2019-09-20 07:05
I think it looks ok? I can't tell for sure though.

![Screenshot 2019-09-20 at 16 54 10](https://user-images.githubusercontent.com/458960/65306157-1728c200-dbc8-11e9-8c00-672ebfcc4352.png)

A Dark Mode issue I am seeing however is that Dark Mode seems to be dependent on the app that invokes Keepassium. So if I launch Keepasium, Dark Mode is enabled correctly. But if I bring up Keepassium using Autofill from an app that doesn't run in or support Dark Mode (i.e. Chrome), Keepassium shows up in Light Mode. I'd prefer to have Keepassium run in the mode that my device is in (Dark Mode) not rely on the app that invoked it. What do you think?

**Comment by keepassium** [comment] 2019-09-20 08:12
Yeah, looks good from here :) I will make a separate issue for the 13.1 font size.

Regarding AutoFill, the color theme is defined by the system. I think Apple’s reason is consistency. Besides, dark AutoFill would look really odd above a light app on an iPad :)

**Comment by ankurkotwal** [comment] 2019-09-20 08:15
Fair enough. 🙂

**Comment by keepassium** [comment] 2019-09-21 08:19
Ok, I've moved the font size to a separate issue. 

The dark mode seems fixed, so I'll close this one. Feel free to re-open if there is anything else dark mode related. Thanks!

**Closed by keepassium** 2019-09-21 08:19 UTC
Labels: bug
