### ISSUE TITLE
Processing master key very slow

### ISSUE THREAD

**Issue by theothermattm** [keepassium/KeePassium#128] opened 2020-10-01 13:06 UTC
**Describe the bug**
Since updating to keepassium 1.17.74 on iOS, my database takes significantly longer to open, hanging on the "Processing master key" step.

**To Reproduce**
1. Add a database to keepassium from iCloud drive
2. Open the database
3. Get the "Processing master key" step for 30+ seconds.

**Expected behavior**
Previously it took 1-3 seconds to open the database.

**Screenshots**
N/A

**User Information (please complete the following information):**
 - Device: iPhone 8
 - OS: 13.7
 - App Version: 1.17.74

**Additional context**
I have set the following from KeepassX (which I use to open my safe on mac)
Keepass database format KDBX 3.1
Decryption time - 2.0s

**Comment by keepassium** [comment] 2020-10-01 14:21
Yep, it's a regression in 1.17.74. Sorry about that. Will be fixed in the next update.

**Comment by theothermattm** [comment] 2020-10-01 14:33
@keepassium thank you for making a great app! If there's anything I can do to help let me know, I don't have iOS experience but do have javascript, database, other experience.

**Closed** 2020-10-02 18:47 UTC
Labels: bug

**Comment by keepassium** [comment] 2020-10-02 18:59
Thank you for the offer, @theothermattm. Since KeePassium has a commercial side as well, I would feel extremely uneasy about accepting voluntary code contributions. So doing it solo feels a necessary part of being honest.

In the meanwhile, the key derivation speed has been fixed and even improved a bit. Automatic updates are scheduled to roll out slowly (during a week), but you can update the app manually and get the latest version right now.
