### ISSUE TITLE
Entry viewer appears empty sporadically

### ISSUE THREAD

**Issue by Daniel451** [keepassium/KeePassium#132] opened 2020-10-12 23:50 UTC
**Describe the bug**
Text of password entries is not readable in dark mode.

**Screenshots**

![](https://abload.de/img/12e2e52e-c01d-4879-8qakjg.jpeg)

**User Information (please complete the following information):**
 - Device: iPad Pro 2020
 - OS: iPadOS 14.0
 - App Version: v1.19.76

**Comment by keepassium** [comment] 2020-10-13 08:55
Thank you for the feedback! 
Can you please confirm that the text is visible in the light mode?

**Comment by Daniel451** [comment] 2020-10-13 12:07
@keepassium oh yes, it is actually also non-visible in light mode.

**Comment by keepassium** [comment] 2020-10-13 19:03
Thanks, Daniel. 

I have 3 or 4 other reports about this issue. It seems to happen anywhere from an old iPhone with iOS 11 to your iPad Pro 2020 with iOS 14, affects only few people, but the cause or solution still remain a mystery to me.

It seems that the system collapses the text part of the entry (the rows in your screenshot are unusually narrow). Which should not and, as far as I understand, cannot be happening.

For one user, restarting the device fixed the issue. For another one, the working solution was to reinstall KeePassium. For the most recent report, none of these helped. The only reliable workaround is to start editing the entry — the editor shows the content normally. However, this is not a viable solution in the long term.

I am still investigating what's going on there, any additional details are welcome.

**Comment by Daniel451** [comment] 2020-10-18 17:24
@keepassium Closing KeePassium and restarting the device did not help, unfortunately. However, after deleting the app, restarting the device, re-installing KeePassium it did work again.

Strange bug, I hope a fix is found soon.

**Comment by Daniel451** [comment] 2020-10-18 17:28
@keepassium I just noticed that after installation, when I first opened KeePassium again, the font size was normal compared to other apps. However, when I just closed and re-opened KeePassium to check that it still works, the font size shrinked significantly (looked like 14pt+ after installation and 8pt now).

Maybe there is some strange bug that causes font size to decrease up to the point where the system does not render it anymore.

**Comment by keepassium** [comment] 2020-10-19 10:10
> Maybe there is some strange bug that causes font size to decrease up to the point where the system does not render it anymore.

Yeah, that was my hypothesis when the issue was first reported. Maybe the text scale is reset to zero for some weird reason. So I forced the scale coefficient to be in range 0.5–2.0 in all cases. But that [was back in 1.17](https://github.com/keepassium/KeePassium/blob/master/CHANGELOG.md#11774---2020-09-19)...

Can you zoom the text with two-finger pinch?

**Comment by keepassium** [comment] 2021-01-31 23:37
Ok, I have never found the cause, but this should hopefully be fixed in v1.21.81 released today.

And there is a "troubleshooting" step. If the issue repeats, open KeePassium settings → About, scroll to the end and tap _Reset entry text size to default_. I cannot guarantee this would fix the problem, but either result should clarify whether I was looking in the right place.

(I will keep the issue open for a while, and close it later if there are no new reports.)

**Comment by Daniel451** [comment] 2021-02-07 00:30
@keepassium thanks for the Update!

**Comment by keepassium** [comment] 2021-02-25 21:54
The issue was caused by pinch-to-zoom gesture for resizing entry text. I have moved it to app settings instead (more obvious, less problematic). So the issue was fixed in 1.22.82.

**Closed by keepassium** 2021-02-25 21:54 UTC
Labels: bug
