### ISSUE TITLE
Touch ID prompt is invisible on iPhone with iOS 13

### ISSUE THREAD

**Issue by georgesnow** [keepassium/KeePassium#70] opened 2019-10-11 10:45 UTC
iOS 13.1.1
KeePassium 1.05

Launch app I just get gray screen with the logo on it

**Comment by keepassium** [comment] 2019-10-11 15:59
Hi, thanks for the report! 

Does this look similar to #66? (I thought I've fixed it...)

Also, on which device does this happen?

**Comment by georgesnow** [comment] 2019-10-11 16:18
well not actually the same. it has the symbol on it

iPhone 7

see below:

![IMG_1130](https://user-images.githubusercontent.com/12751441/66667511-2e842980-ec21-11e9-8b6a-1e903db24197.png)

**Comment by keepassium** [comment] 2019-10-11 16:25
Most likely, there is a Touch ID prompt — but it's invisible because of [this Touch ID bug in iOS 13](https://9to5mac.com/2019/09/30/ios-13-iphone-touch-id-login-bug/).

Try to place your finger on the Home button (no pressing, just a Touch ID scan). If the app opens, that was the "invisible Touch ID" thing. It should be fixed in one of the future iOS 13 updates.

**Comment by georgesnow** [comment] 2019-10-11 16:26
I would but I broke my Touch ID ....

**Comment by georgesnow** [comment] 2019-10-11 16:27
and I guess there is no fail over to prompt for a full password?

**Comment by keepassium** [comment] 2019-10-11 17:12
Try to disable Touch ID system-wide (device Settings — Touch DI & Passcode — Finger 1 — Delete Fingerprint. (Repeat for all fingers, as needed.)

After that, KeePassium will fallback to App Lock PIN instead of Touch ID.

**Comment by georgesnow** [comment] 2019-10-11 17:32
I had already turned off Touch ID system when I broke it.

**Comment by georgesnow** [comment] 2019-10-11 17:33
and the finger prints are deleted

**Comment by keepassium** [comment] 2019-10-11 19:15
Hmm, ok... Try to reinstall KeePassium, then. This will reset any settings that could be causing the issue. 

(This will also wipe out the in-app storage, so if you have a local database, you might want to copy it somewhere first.)

**Comment by keepassium** [comment] 2019-10-14 10:01
@georgesnow, any updates on this?

**Comment by georgesnow** [comment] 2019-10-14 16:17
Removing it did fix it. Curious if you consider adding button for after canceling Touch ID or displays as option to just enter the full password. I have 2 keepass apps (Just in case for this situation)and after breaking Touch ID I couldn’t get into either without 100% removal which seems rather drastic

**Comment by keepassium** [comment] 2019-10-14 19:17
> Curious if you consider adding button for after canceling Touch ID or displays as option to just enter the full password.  

There *is* a cancel button, and it is called "Use Passcode" :)

![Touch ID prompt](https://user-images.githubusercontent.com/38399598/66775723-00267880-eec5-11e9-8714-31408f8b2785.PNG)

The problem is that you could not see the Touch ID prompt, because iOS 13 is full of surprises. Combine a broken Touch ID scanner with an [invisible Touch ID prompt](https://9to5mac.com/2019/09/30/ios-13-iphone-touch-id-login-bug/) — and you are stuck with an unresponsive app, that waits for the correct fingerprint but will never receive it. An unfortunate coincidence indeed...

> I had already turned off Touch ID system when I broke it.

I just checked: turning off the switches in the "Use Touch ID for" settings is not enough. You need to delete the fingerprints data. Only in this case the system tells the apps that Touch ID is not available.

P.S. It's probably too late, but if you rotate the phone, the invisible Touch ID prompt appears and you can cancel it.

**Comment by shad0whawk** [comment] 2019-10-16 04:08
I have this same issue occasionally but I’m using Face ID on iOS 13.1.3. Usually after force closing the app a few times and restarting I can avoid the issue.

**Comment by keepassium** [comment] 2019-10-16 18:52
1Password folks [say](https://discussions.agilebits.com/discussion/107974/issues-with-password-autofill-when-using-ios-13-freezing-crashing-delays-touch-id-face-id) this is fixed in iOS 13.2.

**Closed** 2019-11-27 23:24 UTC
Labels: bug
